name: Add release asset

on:
  release:
    types: [published]

jobs:
  add-release-asset:
    runs-on: ubuntu-24.04

    steps:
      - name: check out sources
        uses: actions/checkout@v3
      - name: install fonts
        run: sudo apt-get update -y && sudo apt-get install -y fonts-dejavu fontconfig
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'
      - name: build asset
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: fetch latest release
        id: fetch_release
        uses: thebritican/fetch-latest-release@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: calculate asset name
        id: vars
        run: |
          TAG_NAME=${{ steps.fetch_release.outputs.tag_name }}
          echo ::set-output name=asset_name::Quick Mock-${TAG_NAME:1}.zip
      - name: upload release asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.fetch_release.outputs.upload_url }}
          asset_path: build/distributions/${{ steps.vars.outputs.asset_name }}
          asset_name: ${{ steps.vars.outputs.asset_name }}
          asset_content_type: application/zip
