name: Test plugin

on:
  push:

jobs:
  test-plugin:
    runs-on: ubuntu-18.04

    steps:
      - name: check out sources
        uses: actions/checkout@v2
      - name: install fonts
        run: sudo apt-get update -y && sudo apt-get install -y fonts-dejavu fontconfig
      - name: setup java
        uses: actions/setup-java@v1
        with:
          java-version: '8'
      - name: test plugin
        uses: eskatos/gradle-command-action@v2.0.1
        with:
          arguments: :cleanTest :test check verifyPlugin
