name: Test plugin

on:
  push:

jobs:
  test-plugin:
    runs-on: ubuntu-18.04

    steps:
      - name: check out sources
        uses: actions/checkout@v3
      - name: install fonts
        run: sudo apt-get update -y && sudo apt-get install -y fonts-dejavu fontconfig
      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: '11'
      - name: test plugin
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :cleanTest :test check verifyPlugin
